function z = countAlignedaa(alignment)

% input: alignment generated by swalign function

counter = 0;


for i = 1:size(alignment,2)
    if alignment(1,i) == alignment(3,i)
        counter = counter + 1;
    end
    
end


fractionAlign = counter/size(alignment,2);

disp(['Fraction aligned is: ' num2str(fractionAlign)]);

end
